{% set name = "trame-vtklocal" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/trame_vtklocal-{{ version }}.tar.gz
  sha256: 4042fc2f0354f814d0fbc38ca9506229b58f1ae682c00201fa7f9db52dbe119b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - trame
    - vtk

test:
  imports:
    - trame
    - trame_vtklocal
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/Kitware/trame-vtklocal
  summary: VTK Local Rendering using WASM
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jourdain
    - ayenpure
