{% set name = "trame-vtklocal" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/trame_vtklocal-{{ version }}.tar.gz
  sha256: 90791e2ec4da8149e6896dc1e1987677d7e9e5169e287e4e051f68056bed7ea0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - trame
    - vtk

test:
  imports:
    - trame
    - trame_vtklocal
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/Kitware/trame-vtklocal
  summary: VTK Local Rendering using WASM
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jourdain
    - ayenpure
